swagger: '2.0'
info:
  version: 0.0.0
  title: Simple API
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /availability-requests:
    post:
      responses:
        '200':
          description: OK
  '/availability-requests/stats':
    get:
      responses:
        '200':
          description: OK
  '/availability-requests/{id}':
    get:
      responses:
        '200':
          description: OK
  '/availability-requests/{id}/cancel':
    post:
      responses:
        '200':
          description: OK
  '/availability-requests/{id}/all':
    get:
      responses:
        '200':
          description: OK
